### ISSUE TITLE
crsearch.jsonフォーマット (v1)

### ISSUE THREAD

**Issue by saki7** [cpprefjp/crsearch#1]
Wiki: [crsearch.jsonフォーマット](https://github.com/cpprefjp/crsearch/wiki/crsearch.json%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88)

イメージとしてはこんな感じ…… @melpon

**Comment by saki7** [comment]
書いてて思ったんですが、 `Index::target`,  もしかするとこれ要らないですね。cpprefjpの中身が「ものすごくきれい」で、全部の相対パスが完全に統一されているなら、ですが。

**Comment by melpon** [comment]
`Index::type` ですが、[既存のメタ情報のドキュメント](https://github.com/cpprefjp/site/blob/master/editors_doc/specialized.md#%E3%83%A1%E3%82%BF%E6%83%85%E5%A0%B1)を見ると、

> [meta id-type]: 識別子の種別を表すメタ情報。class, class template, function, function template, enum, variable, type-alias, macro, namespace

とあるので、enum, variable, type-alias あたりも必要そうです。

あと `match_string` というのは、例えばそのページの概要とか検索用単語とかを入れておくと、それで引っ掛けてくれる的な感じでしょうか。

**Comment by saki7** [comment]
> enum, variable, type-alias あたりも必要そうです

この辺を踏まえて、全体的に書き直しました（もっかいレビューお願いします）。  
必要最小限の書き方で「思った通り」にインデックスされるような設計にしようと思って頑張ったのですが、こんな感じでどうでしょうか。

> match_string

これはあまりにも雑すぎたので `article` という type に変更しました。  
そのかわり、`Index::related_to` というメンバを追加したので、これでいい感じになるような気がします。

**Comment by saki7** [comment]
列挙すべき物をStringで扱っている関係で、多少jsonのサイズが大きくなるような気がしますが、現実的には問題にならないと思います。

**Comment by saki7** [comment]
> それより、今回の僕の編集で Index が再帰するようになったせいで、jsの実装の方で遅延評価する必要性が出てきて頭が痛いです

この問題があったので **Index** を **IndexID** と **Index** に分けました。

分ける前

https://github.com/cpprefjp/crsearch/wiki/crsearch.json%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88/2321d17ed2fc57ff4fc212df722b681ea20a6561

分けた後（現行）

https://github.com/cpprefjp/crsearch/wiki/crsearch.json%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88/9a441c8222fde7e978ddb6efe46bc256b8eb33b5

**Comment by faithandbrave** [comment]
バージョンについてです。

> version と C++XX の対応
> 
> ISO/IEC 規格が発効する前は "1z" のような文字列
> その後は "17" のような文字列

C++17からは3年周期のバージョンアップで、仕様が固まったものから順次リリースという体制になったので、仮名称を使う必要はなくなりました。
ですので、最初からC++20とかを使って大丈夫です。

- [cpprefjpサイトでの次期C++バージョンの取り扱い方針](https://github.com/cpprefjp/site/issues/454)

**Comment by saki7** [comment]
おお、そうなんですね。知りませんでした。該当箇所を変更しておきます。

**Comment by saki7** [comment]
- `Namespace::version` -> `Namespace::cpp_version`
- 説明を削除（テーブルに移動）

**Comment by melpon** [comment]
`Index::page_id` は、多分常に設定すると思うので必須でも大丈夫です。

とりあえず `related_to` を考慮しない状態でインデックスを作っていこうと思います。

**Comment by saki7** [comment]
> Index::page_id は、多分常に設定すると思うので必須でも大丈夫です。

メンバ関数の名前とそれに対応するファイル名は全て統一されているようなので、自動生成できると思います。  
これを全て手動で指定してしまうと、jsonのファイルサイズが膨れ上がると思うんですよね。  
article などは常に指定する必要があると思います。

> とりあえず related_to を考慮しない状態でインデックスを作っていこうと思います。

おっけーです。

**Comment by melpon** [comment]
なるほど、サイズ対策ですか…。
では、ひとまずは全部入れて作りますが、自動で解決できそうな場所は後で削っていくことにします。

**Comment by saki7** [comment]
一応：自動生成はjs側でやるので、site_generatorの方では何もしなくて大丈夫ですよ。  
「これ自動でいけそうだな」という感じの項目は直感でスキップしてよいかと。

**Comment by saki7** [comment]
@melpon 

すみません、仕様を１箇所変更しました。

- `Index::cpp_namespace` -> `IndexID::cpp_namespace` （移動）

同じ名前の物が別の名前空間に存在する可能性があるので、たぶんidの方で持たせないとだめかなと。  
致命的な問題が見つからない限り、jsonの仕様は一旦これで固めたいと思います。

**Comment by melpon** [comment]
了解です。`related_to` に作る場合には `IndexID::cpp_namespace` を省略していいですよね？

**Comment by melpon** [comment]
とりあえず作りました。大体イメージと合ってるか確認して貰えると。

以下のファイルを対象にした変換です。

- `reference/array.md`
- `reference/array/op_less.md`
- `reference/algorithm/all_of.md`
- `reference/vector.md`
- `reference/vector/push_back.md`
- `reference/vector/swap_free.md`

<details>

 <summary>生成結果</summary>

```json
{
    "base_url": "https://cpprefjp.github.io",
    "database_name": "cpprefjp",
    "namespaces": [
        {
            "indexes": [
                {
                    "id": {
                        "cpp_namespace": [
                            "std"
                        ],
                        "key": [
                            "array"
                        ],
                        "type": "class"
                    },
                    "page_id": "array"
                },
                {
                    "id": {
                        "cpp_namespace": [
                            "std"
                        ],
                        "key": [
                            "vector"
                        ],
                        "type": "class"
                    },
                    "page_id": "vector"
                }
            ],
            "namespace": [
                "reference"
            ],
            "path_prefixes": [
                "reference"
            ]
        },
        {
            "indexes": [
                {
                    "id": {
                        "cpp_namespace": [
                            "std"
                        ],
                        "key": [
                            "all_of"
                        ],
                        "type": "function"
                    },
                    "page_id": "all_of"
                }
            ],
            "namespace": [
                "reference",
                "algorithm"
            ],
            "path_prefixes": [
                "reference",
                "algorithm"
            ]
        },
        {
            "indexes": [
                {
                    "id": {
                        "cpp_namespace": [
                            "std"
                        ],
                        "key": [
                            "operator<"
                        ],
                        "type": "function"
                    },
                    "page_id": "op_less"
                }
            ],
            "namespace": [
                "reference",
                "array"
            ],
            "path_prefixes": [
                "reference",
                "array"
            ]
        },
        {
            "indexes": [
                {
                    "id": {
                        "cpp_namespace": [
                            "std"
                        ],
                        "key": [
                            "push_back"
                        ],
                        "type": "mem_fun"
                    },
                    "page_id": "push_back"
                },
                {
                    "id": {
                        "cpp_namespace": [
                            "std"
                        ],
                        "key": [
                            "swap (\u975e\u30e1\u30f3\u30d0\u95a2\u6570)"
                        ],
                        "type": "function"
                    },
                    "page_id": "swap_free"
                }
            ],
            "namespace": [
                "reference",
                "vector"
            ],
            "path_prefixes": [
                "reference",
                "vector"
            ]
        }
    ]
}
```

</details>

## 妥協した点

- `Namespace::namespace` に何を入れればいいか分からなかったので、`Namespace::path_prefixes` と同じ値を入れました。
- `Index::id` から作る `IndexID::key` には、とりあえず md ファイルに書かれているタイトルを入れておくので十分そうなので、そうしました。
- `Index::id` から作る `IndexID::type` は基本的にメタ情報の id-type を見て作ってるのですが、id-type の入ってないページ（`article/cpp11.md` とか `reference.md` とか）はどうしようか悩んで、結局今回サンプルで作るのには入れないことにしました。

**Comment by saki7** [comment]
さっそく作って頂きありがとうございます。

問題がありそうな所を踏まえて、仕様を少し修正しました。

- `Namespace::path_prefixes` -> (optional) へ変更、想定される挙動の説明を追記
- `IndexID::type` -> `meta` を追加、全体の説明を加筆修正

---

> Namespace::namespace に何を入れればいいか分からなかったので、Namespace::path_prefixes と同じ値を入れました。

**Index** は基本的に親の `Namespace::namespace` でグルーピングする想定です。  
ただ、 **Namespace** は `cpp_version` でタグ付けするつもりなので、その場合に `namespace` が同一だと、URLにおけるパスが同じになってしまうと思います。

そういう場合に限って、 `......./cpp11/......` のようなパスに上書きする用途で  `path_prefixes` を設けてありました。説明不足だったのでWikiの方にも説明を追記しました（すいません）。

> Index::id から作る IndexID::key には、とりあえず md ファイルに書かれているタイトルを入れておくので十分そうなので、そうしました。

article とかの場合ですよね。それでOKです。

> Index::id から作る IndexID::type は基本的にメタ情報の id-type を見て作ってるのですが、id-type の入ってないページ（article/cpp11.md とか reference.md とか）はどうしようか悩んで、結局今回サンプルで作るのには入れないことにしました。

おそらく、「既存の記事をまとめるためのページ」のことだと思います。これ用に `IndexID::type` に `meta` という種類を追加してみました。他に考えられるエッジケースがもしあればおしえてください。

> related_to に作る場合には IndexID::cpp_namespace を省略していいですよね？

省略してOKです。同じ名前の物が複数の名前空間に存在することも考えられるので、その場合に省略すると `std` として扱うようにします（Wikiにも記載しておきました）

**Comment by melpon** [comment]
https://github.com/cpprefjp/crsearch/pull/2#issuecomment-325214565

に書いている通り、reference 以下の md ファイルを `Namespace::namespace="reference"` にしてやっていたのですが、`Namespace::namespace` は同じだけど `Namespace::path_prefix` が異なるものはどう扱えばいいですか？

例えば `reference/vector.md` と `reference/vector/push_back.md` を変換した結果は以下のようになりました。
しかし、これは `Namespace::namespace` のユニーク性に引っかかるのでどうしましょう。

```json
{
    "base_url": "https://cpprefjp.github.io",
    "database_name": "cpprefjp",
    "namespaces": [{
        "indexes": [{
            "id": { ... },
            "page_id": "vector"
        }],
        "namespace": ["reference"],
        "path_prefixes": ["reference"]
    }, {
        "indexes": [{
            "id": { ... },
            "page_id": "push_back"
        }],
        "namespace": ["reference"],
        "path_prefixes": ["reference", "vector"]
    }]
}
```

**Comment by melpon** [comment]
あと `regex::regex_constants` は `id-type` が `namespace` みたいなのですが、`IndexID::type` には `namespace` が無いのでどう分類しましょう。
https://cpprefjp.github.io/reference/regex/regex_constants.html

**Comment by saki7** [comment]
こんな感じです。

```json
{
    "base_url": "https://cpprefjp.github.io",
    "database_name": "cpprefjp",
    "namespaces": [{
        "indexes": [{
            "id": { "type": "class", "key": ["vector"] },
            "page_id": "vector" // <- 省略可能
        }],
        "namespace": ["reference"],
        "path_prefixes": ["reference"] // <- 省略可能
    }, {
        "indexes": [{
            "id": { "type": "mem_fun", "key": ["vector", "push_back"] },
            "page_id": "push_back" // <- 省略可能
        }],
        "namespace": ["reference"],
        "path_prefixes": ["reference"] // <- 省略可能
    }]
}
```

**Comment by saki7** [comment]
`regex::regex_constants` など、名前空間については、いらないかなと思って `IndexID::type` に `"namespace"` を入れてなかったんですが、あった方がよさそうですね。Wikiに追加します。

**Comment by saki7** [comment]
`Namespace::path_prefixes` は、基本的に `Namespace::cpp_version` を明示して C++XX 固有のタグ付けをするときに使います。それ以外では気にしなくて良いです。

たとえば、 `emplace_back()` 系の関数はC++11から導入されました。  
cpprefjpに既にある記事でそれが明らかな場合は、`Namespace::cpp_version` を `"11"` にした Namespace オブジェクト以下に Index を突っ込んでください。

具体的には、C++98 とか C++03 からある一般的な関数たちは大体 `Namespace::namespace == ["reference"]` のオブジェクトに入れます。 C++11 から入った物は、 `Namespace::namespace == ["reference"]` かつ `Namespace::cpp_version == "11"` 以下に入れます。

- 98, 03系 のリファレンス
  - `Namespace::namespace == ["reference"]`
  - `Namespace::cpp_version なし`
  - vector::push_back, vector::begin, etc...
- 11, 14, それ以降のリファレンス
  - `Namespace::namespace == ["reference"]`
  - `Namespace::cpp_version == "11"` (数字は対応するバージョン）
  - `Namespace::path_prefix == なし` （同じURL以下なので）
  - vector::emplace_back, algorithm::any_of, etc...
- 11, 14, それ以降の言語機能
  - `Namespace::namespace == ["lang"]`
  - `Namespace::cpp_version == "11"` (数字は対応するバージョン）
  - `Namespace::path_prefix == ["lang", "cpp11"]`
  - エイリアステンプレート, 移譲コンストラクタ, etc...

**Comment by melpon** [comment]
> こんな感じです。

なるほど。
ただ実装を見る限り、`path_prefixes/page_id` で URL を作ってたので、`reference/vector/push_back.html` が `reference/push_back.html` になるんじゃないかなという心配があります。

`key` を URL の一部として作るなら、それでうまく URL が作れるように `key` に入れるようにします。
ただ、`key` は `std::vector::push_back` などの表示に使ってたみたいなので、URL とちゃんと一致するかどうかが気になるところです（`key` の最後の要素は `page_id` で上書きできるので問題ないですが）。

**Comment by saki7** [comment]
> ただ実装を見る限り、path_prefixes/page_id で URL を作ってたので、reference/vector/push_back.html が reference/push_back.html になるんじゃないかなという心配があります。

たぶんそうなります。 `Index::page_id` を配列にしましょうか。 `["vector", "push_back"]` とか入れられれば大丈夫そうです。

> key を URL の一部として作るなら、それでうまく URL が作れるように key に入れるようにします。

key は C++のコードと同じ名前でおねがいします（検索にそのまま使います）。 URL の自動生成がうまくいかないのは page_id で対応しましょう

**Comment by saki7** [comment]
補足です。

具体的なURL生成の実装を僕が示していなかったので、 `Namespace::path_prefix` が謎なのだと思います。

js側の Index のURL生成は、以下のようなステップで実装されます。

0. `CRSearch::base_url` を見る （例： `"https://cpprefjp.github.io"`）
1. `Namespace::namespace` を見る （例： `["reference"]`）
2. `Namespace::cpp_version` を見る （例： `"11"`）
3. `Namespace::path_prefix` を見る （例： 無し）
4. `IndexID::type` を見る （例： `"function"`）
5. `IndexID::cpp_namespace` を見る （例： `["std", "chrono"]` ）
6. `IndexID::key` を見る （例： `"duration_cast"`）
7. 全部 join する

この例で7まで行った時、まず 0〜3の情報でベースのURLを作ります。

```
https://cpprefjp.github.io/reference
```

次に、4〜6で相対パス以下をアペンドします。

```
https://cpprefjp.github.io/reference/chrono/duration_cast.html
```

page_id の指定がある場合は、 `https://cpprefjp.github.io/reference/************` の末尾の生成に使います。

**Comment by melpon** [comment]
> `Index::page_id` を配列にしましょうか。

なるほどその手が。了解です。それで作ってみます！

**Comment by saki7** [comment]
`Index::page_id` は、もともと

1. `operator[]` -> `op_at.html` のようなイレギュラーな物への対応
2. 記事（タイトルをそのままURLにできないもの）への対応

この２つを目的として入れました。なので、 (2) では必須ですが、 本来は (1) では僕が頑張れば全部自動化できます。ただし、実装するうちにコーナーケースが幾らでも出てきそうな気がしてますし、めるぽんさんがとりあえず全部入りで生成してくれてるので後回しにしてます。

**Comment by saki7** [comment]
@melpon ひとまず、 daeef05489d092a4164109fa234fb255bb321941 でここまでの対応をしました。手元では動いてます。見てみてください〜

**Comment by saki7** [comment]
https://github.com/cpprefjp/crsearch/issues/1#issuecomment-327206039

上のコメントが分かりづらかったので、加筆しました。

**Comment by melpon** [comment]
`reference/` の下だけ、かつまだ `Namespace::cpp_version` で分けていないのを置いときました。
https://raw.githubusercontent.com/cpprefjp/crsearch/v1-with-docker/example/crsearch.json

なので残りは

- `lang/` 以下の対応
- `Namespace::cpp_version` 追加

だけすれば完了かな

**Comment by melpon** [comment]
あ、あと `related_to` を（ありそうなら）入れていくっていうのもあるんだった。
メタデータに header や class があったらそれを入れていく感じかな。

**Comment by melpon** [comment]
実装しました（容量削減以外）。URL は↑のままです。（581KB）

**Comment by saki7** [comment]
https://github.com/cpprefjp/crsearch/pull/2#issuecomment-328015736 の続き

結構ざっくり修正入れたので、見て頂ければ。

generatorの方でお願いしたいこと：

- lang/cpp11.md のようなページを `IndexID::type == "meta"` として扱いたい
  - md 内に `[meta cpp]` が無い場合に特別扱いすれば可能でしょうか。
- non-member operator function を除外したい （[例](https://cpprefjp.github.io/reference/iterator/reverse_iterator/op_minus.html)）
  - 現行だと `"(非メンバ関数)"` という名前がついていたりする

---

容量削減はどうしましょうか。正直3MBくらいあるかと思ってたので、581KBならなんとかなりそうです。今考えてます

**Comment by saki7** [comment]
容量の目標としては、jsonがuncompressedで200KB未満くらいかな。

**Comment by melpon** [comment]
> lang/cpp11.md のようなページを IndexID::type == "meta" として扱いたい

lang 下だけの対応で良ければ、「lang 直下の md ファイルだけ "meta" にする」という特別扱いするのは可能です。

> non-member operator function を除外したい

タイトルに "(非メンバ関数)" が付いてたら除外する、というのは簡単にできますが、その対応で良さそうです？

**Comment by faithandbrave** [comment]
"(非メンバ関数)"は、`std::swap()`のオーバーロードとかメンバ関数との区別のために付けていますが、演算子にはついてない場合がありますね・・・。
https://cpprefjp.github.io/reference/vector/swap_free.html
https://cpprefjp.github.io/reference/vector/op_equal.html

**Comment by saki7** [comment]
考えてみましたけど、やっぱ無理っすね……。ごめんなさい！！

@melpon 

related_to 対応するときに、
ページに `[meta header]` があった場合に、 `type = `"header"`` な IndexID を `related_to` に突っ込んでもらうことってできますか？

**Comment by saki7** [comment]
>> lang/cpp11.md のようなページを IndexID::type == "meta" として扱いたい

> lang 下だけの対応で良ければ、「lang 直下の md ファイルだけ "meta" にする」という特別扱いするのは可能です。

それでお願いします。もともと meta はUX的な理由で入れてるので、ここではアドホックな対応でも大丈夫だと思います。

**Comment by saki7** [comment]
残りは、 

- `Namespace::cpp_version` 対応
- `related_to` 追加対応
- 容量削減

ですね。結構流れがいい感じで来てるので、 related_to も v1 に入れてしまいたいですね。

**Comment by melpon** [comment]
> Namespace::cpp_version 対応
> related_to 追加対応

どっちも既に対応してると思うので、確認してみて下さい。

**Comment by melpon** [comment]
> それでお願いします。もともと meta はUX的な理由で入れてるので、ここではアドホックな対応でも大丈夫だと思います。

了解です！

**Comment by melpon** [comment]
「lang 直下の md ファイルだけ "meta" にする」対応しました https://raw.githubusercontent.com/cpprefjp/crsearch/v1-with-docker/example/crsearch.json

**Comment by saki7** [comment]
>> Namespace::cpp_version 対応
>> related_to 追加対応

> どっちも既に対応してると思うので、確認してみて下さい。

すいません、最新のjsonにマージはしたんですが、ブラウザで見てたのが古いバージョンでした……

> 「lang 直下の md ファイルだけ "meta" にする」対応しました 

あざす。

---

容量削減を軽く試してみましたけど、結構大変ですねこれ。

### 容量削減（自明なもの）

- `"cpp_version": ["std"]` 完全一致の時だけomit (-61KB)

簡単にできそうなのは、これくらいしかないです。

逆に言うと、現時点で容量を食ってるのはほとんど related_to なので、

### 容量削減（大幅な変更が必要なもの）

- IndexIDにサロゲートキーを入れる
- Namespaceに IndexID の一覧を持たせる
- Index::id, Index::related_to では サロゲートキーを参照

これで、少なく見積もっても 200KB くらいは削減できると思います。  
あまりやりたくはないですが、 500KB は流石に厳しいのでお願いせざるをえない気がします……

容量削減について、なにか良い案はありますか？

**Comment by melpon** [comment]
> "cpp_version": ["std"] 完全一致の時だけomit (-61KB)

これをすると「namespace メタデータに std が入っていた場合」と「そもそもメタデータに namespace の指定が存在していない場合」の区別が付かなくなりますけど大丈夫そうですか？

> 容量削減（大幅な変更が必要なもの）

対応するのはそんなに大変でも無いので大丈夫です。

**Comment by saki7** [comment]
> これをすると「namespace メタデータに std が入っていた場合」と「そもそもメタデータに namespace の指定が存在していない場合」の区別が付かなくなりますけど大丈夫そうですか？

あー。ちょっとこれはもう一度考えます……。

>> 容量削減（大幅な変更が必要なもの）

> 対応するのはそんなに大変でも無いので大丈夫です。

では、お願いします。

Wikiの方にIndexIDを持たせるように修正を入れておきます

**Comment by saki7** [comment]
Wikiを修正しました。

**Comment by melpon** [comment]
サロゲートキーを参照するようにしてみましたが、433KBまでしか減らないですね…

**Comment by melpon** [comment]
読みにくくなりますが、順序さえ規定してしまえばキー名が無くても良くなるので、そういう方向で対応するとかですかねぇ…

**Comment by melpon** [comment]
無駄な空白あったので削ったら388KB

**Comment by melpon** [comment]
IndexID を配列にしたら 388KB → 303KB
Index を配列にしたら 388KB → 311KB
両方適用したら 388KB → 227KB

**Comment by saki7** [comment]
@melpon 全部最適化した状態のjsonってどんな感じです？

**Comment by melpon** [comment]
こんな感じです。
https://raw.githubusercontent.com/cpprefjp/crsearch/v1-with-docker/example/crsearch-optimized.json

（そういえばJSONの日本語をそのまま出すようにもしました）

**Comment by saki7** [comment]
実際見ると破壊力やばいですねこれ。

……誰もメンテできなくなりそうなので、流石にこれはやめましょうｗ

サロゲートキーバージョン＋空白削減で388KBなんですよね。それくらいなら許容範囲だと思うので、それでいきましょうか。そっちをうｐして頂けますか？

**Comment by melpon** [comment]
アップしましたー: https://raw.githubusercontent.com/cpprefjp/crsearch/v1-with-docker/example/crsearch.json

**Comment by yumetodo** [comment]
`s/コンストラクタ/ctor/`
`s/デストラクタ/dtor/`
したらもう少し減らないかな、js側で対処・・・いや、コスパに見合わないか

**Comment by saki7** [comment]
@melpon
ありがとうございます。これをもとに最終調整したいと思います。

---

@yumetodo 

そのへんは既に現行のjsで `(constructor)` などに置換して処理してます。これはサイズとか英語を理由とした対処ではなく、検索性のためです。ちなみにやったところでコストはほぼかかりません

ところで、数百キロバイト規模の削減で悩んでいる現状なのに、たかだか単位あたり5文字×クラス数とかの削減で効果があると思いますか？

はっきり言わせていただきますが、僕はこれ以上不毛な提案とか不毛な議論に付き合う気はありません。

**Comment by saki7** [comment]
あと、このIssueはjsonのフォーマットについて議論するIssueです。具体的に言うと、問題の解決にスキーマの変更が不可欠な場合にここで議論してます。

UI/UX周りの問題・バグ・改善点がある場合はここではなく #2 の方にお願いします。

**Comment by saki7** [comment]
最後まで実装しましたが、スキーマに問題がもう無いので閉じます。ご協力ありがとうございました。
