### ISSUE TITLE
id-type が付いている header なページが存在しないものとして扱われる

### ISSUE THREAD

**Issue by saki7** [cpprefjp/crsearch#19]
- `<string` -> 表示される
- `<vector` -> 無い
- `<bitset` -> 無い

これは元データ的にどうしようもないと思うので、crsearch.jsで対応

**Comment by faithandbrave** [comment]
参考情報として、`<array>`以外のコンテナは、C++17のpolymorphic allocator対応で`std::pmr::vector`とかが必要になるので、ヘッダ階層を作る予定です。その際、ヘッダ階層を全部用意してしまった方がいいかもしれません。

**Comment by faithandbrave** [comment]
cpprefjp/site側でヘッダ階層を全て用意する場合、crsearch側の対応が必要なくなります。
ぼくがいま`<optional>`のリファレンス作成をやっていますが、もうちょっとで終わるので、来週くらいにそっちに取り掛かることはできます。

**Comment by saki7** [comment]
@faithandbrave 情報ありがとうございます！！　「ヘッダページが現時点で存在しない場合は、そのヘッダに確実に含まれていてかつなるべく一番メインっぽいものをヘッダとして表示」という対応にします。なので、cpprefjp/siteを急ぎで修正する必要はありません。
