### ISSUE TITLE
CIのアップデート頻度を上げたい

### ISSUE THREAD

**Issue by saki7** [cpprefjp/crsearch#22]
@melpon 

今はおそらく cpprefjp/site と合わせて更新されているはずで、最長１日とかだと思うのですが、 crsearch がエンバグした場合に最悪丸１日検索が動かないということが起こり得る上に、jsのエラーに引っ張られて左のツリービューや、Googleサイト内検索も死ぬ可能性が少しあります。

できれば crsearch だけ即時 （push トリガー）か、最長でも１５分くらいで本番にデプロイされるようにして貰いたいのですが、お願いできますか？

**Comment by melpon** [comment]
あー、今は手動なんですよね。デプロイサーバが Ubuntu 12.04（TLS のサポート切れてる）で、この上で npm とかちゃんと動くか確認するのが面倒だったから、自分の Mac からコンパイルして push してました。

自動にするのは管理の手間的にも大分良くなると思うので、早めにやります。

**Comment by saki7** [comment]
了解しました。npmやwebpack周りで分からないことがあれば、このIssueでいいので気軽に聞いてください。

**Comment by saki7** [comment]
ちなみに SSH か rsync か Chef か Jenkins か OpsWorks か CircleCI あたりであれば鯖運用してた経験あるのでその辺で何かあればご相談ください

**Comment by melpon** [comment]
とりあえずサポート切れ OS を使うのは微妙なので、アップデートしてみることにしました。
うまく動けば Docker 入れられるのでどうとでもなりそうです。動かなければ何か考えます。

**Comment by saki7** [comment]
@melpon 別件ですが cpprefjp 本体 （つまり site_generator） の闇のタレを一新して細かいデザインの修正を入れようと思っているので 新しくcrsearch と同等のCI環境が必要になるかもしれません

これは急ぎではないのですが、  僕が今後 cpprefjp の本体のデザインの修正を入れる場合は crsearch と同等の開発環境がどうしても必要です。Docker コンテナが２個以上共存できるような設計にしておいていただけると後々嬉しい……）

**Comment by saki7** [comment]
いますでに発生してる懸念としては、例えばこのIssue cpprefjp/site/issues/472 とかはバックエンドの修正は僕がsite_generatorに投げればいいのですが、フロントエンドのCSSがどうしても多少複雑になるので生のCSSだと限界があります。

**Comment by yumetodo** [comment]
なんかどっかで見た話の流れと思ったら私自身が過去に
https://github.com/cpprefjp/site/issues/466
で似た話を投げていた・・・

**Comment by melpon** [comment]
crsearch に push したら自動的に本番に反映されるようにしました。

あと site_generator 側も Docker でいろいろ生成するようにしたので、crsearch を更新したのをローカルで確認したりも出来るはず。
具体的な方法は [site_generator/README.md](https://github.com/cpprefjp/site_generator/blob/master/README.md) に書きました。

**Comment by saki7** [comment]
神すぎる…………………

**Comment by saki7** [comment]
反映されてました。ありがとうございます
