### ISSUE TITLE
非メンバ関数が検索でヒットしない

### ISSUE THREAD

**Issue by saki7** [cpprefjp/crsearch#25]
`operator < optional` とかでヒットしない

**Comment by kariya-mitsuru** [comment]
あっ、これも 27c55041f4ee8d677f588586fb74000640aa2b51 で対応してます。
`operator< optional` の2語であれば欲しい非メンバ関数が出るようになりました。
`operator < optional` の3語だと、`<` 単体があらゆるヘッダにマッチしてしまうので機能しないのですが…

**Comment by kariya-mitsuru** [comment]
`<` 単体の件はともかく、検索自体はうまく動くようになったので、こちらはクローズします。
