### ISSUE TITLE
cpprefjp に適用すると表示が崩れる

### ISSUE THREAD

**Issue by melpon** [cpprefjp/crsearch#4]
https://cpprefjp.github.io/ に適用してみましたが、表示が少し崩れているようです（妙に小さい＆検索ボタンが切れてる）

<img width="1128" alt="2017-10-22 7 54 29" src="https://user-images.githubusercontent.com/816539/31856549-a6dd9e3e-b6fe-11e7-92ce-721dbc1df349.png">

多分 Twitter Bootstrap との相性の問題だと思いますが、CSS よく分からないのでいい感じに合わせて貰えると…。

**Comment by yumetodo** [comment]
現在その辺は`float: left;`を使って横並びにしているようなのですが、この際DOM弄ってflexboxで書き換えてしまうべきかなと思ったりするんですが・・・

というのは、
![image](https://user-images.githubusercontent.com/10869046/31859191-1c4ac932-b743-11e7-96fa-5717bd7c8ab1.png)
のように、Windows幅が狭いときにGoogleカスタム検索が潜り込んでしまっていて、これも直したほうがいいと思うんですが、`float: left;`でその辺頑張るのは大変じゃないですかね・・・？
@saki7

**Comment by saki7** [comment]
@yumetodo これはそもそもサイト上に検索ボックスが２個あること自体が問題なので別のPRで直します

**Comment by saki7** [comment]
@melpon 

#5 をマージした後に #6 をマージ、その後 cpprefjp/site_generator#22 をマージすれば全部解決すると思います。

**Comment by melpon** [comment]
https://cpprefjp.github.io/ に適用しました。いい感じに表示されてますね。ありがとうございます！

**Comment by faithandbrave** [comment]
![2017-10-23 16 55 16](https://user-images.githubusercontent.com/240038/31877920-41d1a2ea-b813-11e7-8ff5-3533df68fa7e.png)

検索アイコンがずれている気がしますが、ぼくだけでしょうか？

**Comment by saki7** [comment]
@faithandbrave すいません！！直します！！
