### ISSUE TITLE
上下キーでナビゲーションするとページが上下に動く

### ISSUE THREAD

**Issue by saki7** [cpprefjp/crsearch#9]
079b86ea51f397defcda9760ca068189c6957da2 の regression

修正は、検索ボックスにフォーカスがあるときだけpreventDefaultする(return false)

**Comment by melpon** [comment]
「検索ボックスにフォーカスがあるときだけ」って条件が無かった…

**Comment by saki7** [comment]
寝て起きたら直ってた！！ありがとうございます！！
